# This is a basic workflow to help you get started with Actions

name: ElectronicsMicrocontrollers_CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: tfwnicholson/platformio:latest

    steps:
      - uses: actions/checkout@v2

      - name: Build code
        run: pio run -v > build.log
      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: build-out
          path: build.log
